# Generated by Django 5.2.4 on 2025-08-01 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_remove_video_tweet_tweet_photo_tweet_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
