# Generated by Django 5.2.4 on 2025-08-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='original_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='tweet.tweet'),
        ),
    ]
